//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.0
//     from Assets/MyInputSystem/Scripts/InputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActions"",
    ""maps"": [
        {
            ""name"": ""LeftHand"",
            ""id"": ""2ab872bb-880e-4826-8b49-6ffc7e5fda2f"",
            ""actions"": [
                {
                    ""name"": ""JoyStickMove"",
                    ""type"": ""Value"",
                    ""id"": ""7a7f4365-453e-42e5-8ccb-ebb317f3964f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TriggerTouchTap"",
                    ""type"": ""Button"",
                    ""id"": ""bc4ff3d1-e5e6-4bea-86e6-2c59c882cbd8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TriggerTouchHold"",
                    ""type"": ""Button"",
                    ""id"": ""398dc36f-45e4-4088-baf7-5b1653cc5d99"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TriggerTouchMultiTap"",
                    ""type"": ""Button"",
                    ""id"": ""1b6e94f8-cc3c-42f7-8243-b3c736df623c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""MultiTap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TriggerPressedTap"",
                    ""type"": ""Button"",
                    ""id"": ""f776da5b-9f67-4713-9591-df9fbf392591"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TriggerPressHold"",
                    ""type"": ""Button"",
                    ""id"": ""cb9354a2-d4d4-4ba2-893a-af5b797413b9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TriggerPressMultiTap"",
                    ""type"": ""Button"",
                    ""id"": ""1b023718-ea97-4025-b664-3926699d4f94"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""MultiTap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GripPressTap"",
                    ""type"": ""Button"",
                    ""id"": ""271c3b4b-88fd-48f1-96a4-93b244e9dab9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GripPressHold"",
                    ""type"": ""Button"",
                    ""id"": ""80d16859-498e-4b89-a777-024f67832d8e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GripPressMultiTap"",
                    ""type"": ""Button"",
                    ""id"": ""aadb533c-3452-43db-af8f-416f01cc01d5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""MultiTap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PrimaryTouchTap"",
                    ""type"": ""Button"",
                    ""id"": ""6acaa0ec-14a7-44fa-9f8b-06e7e0294bef"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PrimaryTouchHold"",
                    ""type"": ""Button"",
                    ""id"": ""897f0ce2-5f10-4e5f-a9ea-6e4c639bab0b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PrimaryTouchMultiTap"",
                    ""type"": ""Button"",
                    ""id"": ""f9a5eb8a-e248-4fd8-a6ec-6a37ca67403a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""MultiTap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PrimaryPressTap"",
                    ""type"": ""Button"",
                    ""id"": ""920014df-36d9-4d3d-b1f8-5e10c91f1c8a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PrimaryPressHold"",
                    ""type"": ""Button"",
                    ""id"": ""6aa01e84-0ab4-434e-b0f8-28c59b7cfd6b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PrimaryPressMultiTap"",
                    ""type"": ""Button"",
                    ""id"": ""a9a77b22-9309-4242-b760-b03949f101b5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""MultiTap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondaryTouchTap"",
                    ""type"": ""Button"",
                    ""id"": ""6a019230-7736-4d88-bf3e-5ab1e98485ca"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondaryTouchHold"",
                    ""type"": ""Button"",
                    ""id"": ""b83ef2b3-1604-44b3-97ef-6c574b08ad43"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondaryTouchMultiTap"",
                    ""type"": ""Button"",
                    ""id"": ""7a26b85d-47ba-48fa-84c0-ac29b2318582"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""MultiTap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondaryPressedTap"",
                    ""type"": ""Button"",
                    ""id"": ""babf6a60-ceb2-48dd-b345-d79591ba0e97"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondaryPressedHold"",
                    ""type"": ""Button"",
                    ""id"": ""a3842172-e766-4355-bc24-a3c4976195ee"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondaryPressedMultiTap"",
                    ""type"": ""Button"",
                    ""id"": ""ac9145e6-8a99-456c-a2e1-126d2668714e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""MultiTap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Menu"",
                    ""type"": ""Button"",
                    ""id"": ""0e7562de-64ba-4815-96a6-6e444c57480b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""4da352a1-e533-4c52-8cba-da702ec800c3"",
                    ""path"": ""<XRController>{LeftHand}/triggerTouched"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TriggerTouchTap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""28d7610b-cf91-48ec-98dd-f971878b5d0e"",
                    ""path"": ""<XRController>{LeftHand}/joystick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""JoyStickMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""96b6af88-8158-441b-8987-c9882a6d3d27"",
                    ""path"": ""<XRController>{LeftHand}/primaryTouch"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryTouchTap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5d0c28ff-4afd-4b48-a80b-84d296af3863"",
                    ""path"": ""<XRController>{LeftHand}/primaryTouch"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryTouchMultiTap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""95363ff7-5c1f-4633-9fcc-7f3cf65e772a"",
                    ""path"": ""<XRController>{LeftHand}/primaryTouch"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryTouchHold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9ae72628-85ba-438f-8a36-bb37038cf401"",
                    ""path"": ""<XRController>{LeftHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryPressMultiTap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f1e9d1be-9168-4b57-af68-b186aab6a322"",
                    ""path"": ""<XRController>{LeftHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryPressTap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c389ed5c-23e9-4004-8db9-5c323274e911"",
                    ""path"": ""<XRController>{LeftHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryPressHold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""98365660-d2ca-4ecd-80fe-746999c7d936"",
                    ""path"": ""<XRController>{LeftHand}/secondaryTouch"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryTouchTap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a63d2cf6-a599-49fe-86fd-9a22af2bc088"",
                    ""path"": ""<XRController>{LeftHand}/secondaryTouch"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryTouchHold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""143eacea-227c-40e8-be3e-e1916e8cf9a7"",
                    ""path"": ""<XRController>{LeftHand}/menuButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c601e0ef-3bb2-4596-b287-e4c227a43e75"",
                    ""path"": ""<XRController>{LeftHand}/gripPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GripPressTap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b4f3e63b-0252-4d8f-abf4-f2a27fa3ae70"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GripPressTap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e9a2479d-c58e-4848-a80f-94474782f31f"",
                    ""path"": ""<XRController>{LeftHand}/gripPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GripPressMultiTap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bc6c1848-8325-4a0b-855a-180bd33bf3f6"",
                    ""path"": ""<XRController>{LeftHand}/triggerTouched"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TriggerTouchHold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bb5d0a78-832e-4f81-95d6-b84424cea829"",
                    ""path"": ""<XRController>{LeftHand}/triggerTouched"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TriggerTouchMultiTap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4be500e6-4b57-48e8-8dc5-5abd02e28db3"",
                    ""path"": ""<XRController>{LeftHand}/triggerPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TriggerPressedTap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6a856ba2-4505-426a-95e8-8f9168376483"",
                    ""path"": ""<XRController>{LeftHand}/triggerPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TriggerPressHold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4fd6229a-6d97-490a-be19-1a84bceb3a6d"",
                    ""path"": ""<XRController>{LeftHand}/triggerPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TriggerPressMultiTap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""45a244c5-5b9c-4863-abca-c1c6d83a4dc0"",
                    ""path"": ""<XRController>{LeftHand}/gripPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GripPressHold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8749541f-18bf-448a-a2a2-4861c6820009"",
                    ""path"": ""<XRController>{LeftHand}/secondaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryPressedHold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fa48cbf6-1b4a-42a2-95d2-a65f0a81cd1e"",
                    ""path"": ""<XRController>{LeftHand}/secondaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryPressedMultiTap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""650d4010-1db9-4ce1-bb66-88f6dc097144"",
                    ""path"": ""<XRController>{LeftHand}/secondaryTouch"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryTouchMultiTap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d7e43279-46fe-4fd4-9676-baa112346f5d"",
                    ""path"": ""<XRController>{LeftHand}/secondaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryPressedTap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""RightHand"",
            ""id"": ""98212f97-32f6-4eac-866c-8a7473352e0d"",
            ""actions"": [
                {
                    ""name"": ""JoyStickMove"",
                    ""type"": ""Value"",
                    ""id"": ""2aad7676-33bb-4e6e-a991-7a9de5f7a729"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TriggerTouchTap"",
                    ""type"": ""Button"",
                    ""id"": ""7e59019f-6da6-4ca8-a42f-84f63c8b4d07"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TriggerTouchHold"",
                    ""type"": ""Button"",
                    ""id"": ""9e2b3235-999f-4bc3-8707-d5576e7dfde4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TriggerTouchMultiTap"",
                    ""type"": ""Button"",
                    ""id"": ""f6587fae-358c-4c66-9801-eb6a90da154d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""MultiTap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TriggerPressedTap"",
                    ""type"": ""Button"",
                    ""id"": ""ddcc497f-ccae-4143-a664-b354ea534d49"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TriggerPressHold"",
                    ""type"": ""Button"",
                    ""id"": ""aff0fc09-c750-4110-b3a6-76362b123413"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TriggerPressMultiTap"",
                    ""type"": ""Button"",
                    ""id"": ""37f0bd7e-2c8f-4a2f-89cf-07d70b8805d6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""MultiTap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GripPressTap"",
                    ""type"": ""Button"",
                    ""id"": ""b53d08b9-128e-4095-9da5-f14a527d5510"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GripPressHold"",
                    ""type"": ""Button"",
                    ""id"": ""d7a2c235-67f4-4ce4-be03-3686216cb7a5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GripPressMultiTap"",
                    ""type"": ""Button"",
                    ""id"": ""e9228ab7-1df5-4e06-bd3c-f54e30142fee"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""MultiTap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PrimaryTouchTap"",
                    ""type"": ""Button"",
                    ""id"": ""6d2be7eb-30cb-431b-9a7f-b0b5b14ce5d5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PrimaryTouchHold"",
                    ""type"": ""Button"",
                    ""id"": ""7f6233a8-2721-4067-a129-8817dca0e30b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PrimaryTouchMultiTap"",
                    ""type"": ""Button"",
                    ""id"": ""c3f78ec8-682d-457d-941b-89bbe9f7b581"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""MultiTap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PrimaryPressTap"",
                    ""type"": ""Button"",
                    ""id"": ""41c7dedd-8a9e-4172-ba30-c44edb27f230"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PrimaryPressHold"",
                    ""type"": ""Button"",
                    ""id"": ""d1a73e40-b477-40bf-a981-0a8ead063215"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PrimaryPressMultiTap"",
                    ""type"": ""Button"",
                    ""id"": ""6c6cfb0b-0371-40e7-9445-c0c07ee5a911"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""MultiTap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondaryTouchTap"",
                    ""type"": ""Button"",
                    ""id"": ""7cad86c4-400a-4527-acbd-7d1c0500e909"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondaryTouchHold"",
                    ""type"": ""Button"",
                    ""id"": ""d4d579f0-57ea-4f3f-844d-f2c80f147528"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondaryTouchMultiTap"",
                    ""type"": ""Button"",
                    ""id"": ""68857bb5-c779-45fd-96b6-f91928b867f3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""MultiTap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondaryPressedMultiTap"",
                    ""type"": ""Button"",
                    ""id"": ""4ca35fed-dc4f-4143-9751-b37be933e7f7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""MultiTap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondaryPressedHold"",
                    ""type"": ""Button"",
                    ""id"": ""6dbbd5f6-821b-4fe1-a808-d27ff8af8701"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondaryPressedTap"",
                    ""type"": ""Button"",
                    ""id"": ""ef90cda3-e548-4ea8-9101-8f531a7df63b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Menu"",
                    ""type"": ""Button"",
                    ""id"": ""5d1e4487-5b58-4cee-a985-0880a3ec8118"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""5f3d8b9e-ae5f-485c-b1f8-4645e8fb0244"",
                    ""path"": ""<XRController>{RightHand}/triggerTouched"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TriggerTouchTap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a7ffaa10-a234-47b7-8417-4b2cf8e20edc"",
                    ""path"": ""<XRController>{RightHand}/triggerTouched"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TriggerTouchHold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d242f455-29d6-4c9b-835e-bb1460d9a24d"",
                    ""path"": ""<XRController>{RightHand}/triggerTouched"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TriggerTouchMultiTap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""07046a4c-d7f9-4d21-8ae5-9ddd787cc3d0"",
                    ""path"": ""<XRController>{RightHand}/triggerPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TriggerPressHold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""95fbde0f-7a92-439c-a905-31e978ddbc31"",
                    ""path"": ""<XRController>{RightHand}/triggerPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TriggerPressMultiTap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8af68f4a-d207-4e71-a671-bafb0e4ec179"",
                    ""path"": ""<XRController>{RightHand}/joystick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""JoyStickMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b6186519-617c-44ef-979b-cf2bb1581db4"",
                    ""path"": ""<XRController>{RightHand}/triggerPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TriggerPressedTap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d45cfb24-069e-4449-b96e-a995ea4594e7"",
                    ""path"": ""<XRController>{RightHand}/primaryTouch"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryTouchTap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d25624b5-2a93-4841-967e-0698f2957956"",
                    ""path"": ""<XRController>{RightHand}/primaryTouch"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryTouchMultiTap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8e902bb9-6543-4907-9d05-adc8098331be"",
                    ""path"": ""<XRController>{RightHand}/primaryTouch"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryTouchHold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f2cfdaa5-40bd-4e6b-96b4-0512117f7dd7"",
                    ""path"": ""<XRController>{RightHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryPressMultiTap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0dc45a75-1fea-461d-9231-f85a36637058"",
                    ""path"": ""<XRController>{RightHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryPressTap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""324e0b72-8587-4b24-ae01-b23f30e0b501"",
                    ""path"": ""<XRController>{RightHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryPressHold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""39c20e39-b7fd-4220-84f7-36d84751dc83"",
                    ""path"": ""<XRController>{RightHand}/secondaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryTouchTap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""15f133c2-a0b6-4e3e-b855-243a95321690"",
                    ""path"": ""<XRController>{RightHand}/secondaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryTouchMultiTap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9c402b39-9347-49ea-bed0-69a528c35da2"",
                    ""path"": ""<XRController>{RightHand}/secondaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryTouchHold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8f0117ab-c95c-44d4-8886-d51841059fa0"",
                    ""path"": ""<XRController>{RightHand}/menu"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e3e64d24-8ebc-44f9-a804-a51a4cc35451"",
                    ""path"": ""<XRController>{RightHand}/gripPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GripPressHold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""11684a46-edd9-4df8-9339-06771d72d11d"",
                    ""path"": ""<XRController>{RightHand}/gripPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GripPressTap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f0cdde76-86f7-4ab9-bc39-9d68826d8b65"",
                    ""path"": ""<XRController>{RightHand}/gripPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GripPressMultiTap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0df3ba51-d36b-49af-a05a-659639b597d5"",
                    ""path"": ""<XRController>{RightHand}/secondaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryPressedTap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""593407a6-6fd3-4efc-baec-0c22c0136196"",
                    ""path"": ""<XRController>{RightHand}/secondaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryPressedHold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cf0a2b34-e642-44e6-8091-b237ebf50b38"",
                    ""path"": ""<XRController>{RightHand}/secondaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryPressedMultiTap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // LeftHand
        m_LeftHand = asset.FindActionMap("LeftHand", throwIfNotFound: true);
        m_LeftHand_JoyStickMove = m_LeftHand.FindAction("JoyStickMove", throwIfNotFound: true);
        m_LeftHand_TriggerTouchTap = m_LeftHand.FindAction("TriggerTouchTap", throwIfNotFound: true);
        m_LeftHand_TriggerTouchHold = m_LeftHand.FindAction("TriggerTouchHold", throwIfNotFound: true);
        m_LeftHand_TriggerTouchMultiTap = m_LeftHand.FindAction("TriggerTouchMultiTap", throwIfNotFound: true);
        m_LeftHand_TriggerPressedTap = m_LeftHand.FindAction("TriggerPressedTap", throwIfNotFound: true);
        m_LeftHand_TriggerPressHold = m_LeftHand.FindAction("TriggerPressHold", throwIfNotFound: true);
        m_LeftHand_TriggerPressMultiTap = m_LeftHand.FindAction("TriggerPressMultiTap", throwIfNotFound: true);
        m_LeftHand_GripPressTap = m_LeftHand.FindAction("GripPressTap", throwIfNotFound: true);
        m_LeftHand_GripPressHold = m_LeftHand.FindAction("GripPressHold", throwIfNotFound: true);
        m_LeftHand_GripPressMultiTap = m_LeftHand.FindAction("GripPressMultiTap", throwIfNotFound: true);
        m_LeftHand_PrimaryTouchTap = m_LeftHand.FindAction("PrimaryTouchTap", throwIfNotFound: true);
        m_LeftHand_PrimaryTouchHold = m_LeftHand.FindAction("PrimaryTouchHold", throwIfNotFound: true);
        m_LeftHand_PrimaryTouchMultiTap = m_LeftHand.FindAction("PrimaryTouchMultiTap", throwIfNotFound: true);
        m_LeftHand_PrimaryPressTap = m_LeftHand.FindAction("PrimaryPressTap", throwIfNotFound: true);
        m_LeftHand_PrimaryPressHold = m_LeftHand.FindAction("PrimaryPressHold", throwIfNotFound: true);
        m_LeftHand_PrimaryPressMultiTap = m_LeftHand.FindAction("PrimaryPressMultiTap", throwIfNotFound: true);
        m_LeftHand_SecondaryTouchTap = m_LeftHand.FindAction("SecondaryTouchTap", throwIfNotFound: true);
        m_LeftHand_SecondaryTouchHold = m_LeftHand.FindAction("SecondaryTouchHold", throwIfNotFound: true);
        m_LeftHand_SecondaryTouchMultiTap = m_LeftHand.FindAction("SecondaryTouchMultiTap", throwIfNotFound: true);
        m_LeftHand_SecondaryPressedTap = m_LeftHand.FindAction("SecondaryPressedTap", throwIfNotFound: true);
        m_LeftHand_SecondaryPressedHold = m_LeftHand.FindAction("SecondaryPressedHold", throwIfNotFound: true);
        m_LeftHand_SecondaryPressedMultiTap = m_LeftHand.FindAction("SecondaryPressedMultiTap", throwIfNotFound: true);
        m_LeftHand_Menu = m_LeftHand.FindAction("Menu", throwIfNotFound: true);
        // RightHand
        m_RightHand = asset.FindActionMap("RightHand", throwIfNotFound: true);
        m_RightHand_JoyStickMove = m_RightHand.FindAction("JoyStickMove", throwIfNotFound: true);
        m_RightHand_TriggerTouchTap = m_RightHand.FindAction("TriggerTouchTap", throwIfNotFound: true);
        m_RightHand_TriggerTouchHold = m_RightHand.FindAction("TriggerTouchHold", throwIfNotFound: true);
        m_RightHand_TriggerTouchMultiTap = m_RightHand.FindAction("TriggerTouchMultiTap", throwIfNotFound: true);
        m_RightHand_TriggerPressedTap = m_RightHand.FindAction("TriggerPressedTap", throwIfNotFound: true);
        m_RightHand_TriggerPressHold = m_RightHand.FindAction("TriggerPressHold", throwIfNotFound: true);
        m_RightHand_TriggerPressMultiTap = m_RightHand.FindAction("TriggerPressMultiTap", throwIfNotFound: true);
        m_RightHand_GripPressTap = m_RightHand.FindAction("GripPressTap", throwIfNotFound: true);
        m_RightHand_GripPressHold = m_RightHand.FindAction("GripPressHold", throwIfNotFound: true);
        m_RightHand_GripPressMultiTap = m_RightHand.FindAction("GripPressMultiTap", throwIfNotFound: true);
        m_RightHand_PrimaryTouchTap = m_RightHand.FindAction("PrimaryTouchTap", throwIfNotFound: true);
        m_RightHand_PrimaryTouchHold = m_RightHand.FindAction("PrimaryTouchHold", throwIfNotFound: true);
        m_RightHand_PrimaryTouchMultiTap = m_RightHand.FindAction("PrimaryTouchMultiTap", throwIfNotFound: true);
        m_RightHand_PrimaryPressTap = m_RightHand.FindAction("PrimaryPressTap", throwIfNotFound: true);
        m_RightHand_PrimaryPressHold = m_RightHand.FindAction("PrimaryPressHold", throwIfNotFound: true);
        m_RightHand_PrimaryPressMultiTap = m_RightHand.FindAction("PrimaryPressMultiTap", throwIfNotFound: true);
        m_RightHand_SecondaryTouchTap = m_RightHand.FindAction("SecondaryTouchTap", throwIfNotFound: true);
        m_RightHand_SecondaryTouchHold = m_RightHand.FindAction("SecondaryTouchHold", throwIfNotFound: true);
        m_RightHand_SecondaryTouchMultiTap = m_RightHand.FindAction("SecondaryTouchMultiTap", throwIfNotFound: true);
        m_RightHand_SecondaryPressedMultiTap = m_RightHand.FindAction("SecondaryPressedMultiTap", throwIfNotFound: true);
        m_RightHand_SecondaryPressedHold = m_RightHand.FindAction("SecondaryPressedHold", throwIfNotFound: true);
        m_RightHand_SecondaryPressedTap = m_RightHand.FindAction("SecondaryPressedTap", throwIfNotFound: true);
        m_RightHand_Menu = m_RightHand.FindAction("Menu", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // LeftHand
    private readonly InputActionMap m_LeftHand;
    private List<ILeftHandActions> m_LeftHandActionsCallbackInterfaces = new List<ILeftHandActions>();
    private readonly InputAction m_LeftHand_JoyStickMove;
    private readonly InputAction m_LeftHand_TriggerTouchTap;
    private readonly InputAction m_LeftHand_TriggerTouchHold;
    private readonly InputAction m_LeftHand_TriggerTouchMultiTap;
    private readonly InputAction m_LeftHand_TriggerPressedTap;
    private readonly InputAction m_LeftHand_TriggerPressHold;
    private readonly InputAction m_LeftHand_TriggerPressMultiTap;
    private readonly InputAction m_LeftHand_GripPressTap;
    private readonly InputAction m_LeftHand_GripPressHold;
    private readonly InputAction m_LeftHand_GripPressMultiTap;
    private readonly InputAction m_LeftHand_PrimaryTouchTap;
    private readonly InputAction m_LeftHand_PrimaryTouchHold;
    private readonly InputAction m_LeftHand_PrimaryTouchMultiTap;
    private readonly InputAction m_LeftHand_PrimaryPressTap;
    private readonly InputAction m_LeftHand_PrimaryPressHold;
    private readonly InputAction m_LeftHand_PrimaryPressMultiTap;
    private readonly InputAction m_LeftHand_SecondaryTouchTap;
    private readonly InputAction m_LeftHand_SecondaryTouchHold;
    private readonly InputAction m_LeftHand_SecondaryTouchMultiTap;
    private readonly InputAction m_LeftHand_SecondaryPressedTap;
    private readonly InputAction m_LeftHand_SecondaryPressedHold;
    private readonly InputAction m_LeftHand_SecondaryPressedMultiTap;
    private readonly InputAction m_LeftHand_Menu;
    public struct LeftHandActions
    {
        private @InputActions m_Wrapper;
        public LeftHandActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @JoyStickMove => m_Wrapper.m_LeftHand_JoyStickMove;
        public InputAction @TriggerTouchTap => m_Wrapper.m_LeftHand_TriggerTouchTap;
        public InputAction @TriggerTouchHold => m_Wrapper.m_LeftHand_TriggerTouchHold;
        public InputAction @TriggerTouchMultiTap => m_Wrapper.m_LeftHand_TriggerTouchMultiTap;
        public InputAction @TriggerPressedTap => m_Wrapper.m_LeftHand_TriggerPressedTap;
        public InputAction @TriggerPressHold => m_Wrapper.m_LeftHand_TriggerPressHold;
        public InputAction @TriggerPressMultiTap => m_Wrapper.m_LeftHand_TriggerPressMultiTap;
        public InputAction @GripPressTap => m_Wrapper.m_LeftHand_GripPressTap;
        public InputAction @GripPressHold => m_Wrapper.m_LeftHand_GripPressHold;
        public InputAction @GripPressMultiTap => m_Wrapper.m_LeftHand_GripPressMultiTap;
        public InputAction @PrimaryTouchTap => m_Wrapper.m_LeftHand_PrimaryTouchTap;
        public InputAction @PrimaryTouchHold => m_Wrapper.m_LeftHand_PrimaryTouchHold;
        public InputAction @PrimaryTouchMultiTap => m_Wrapper.m_LeftHand_PrimaryTouchMultiTap;
        public InputAction @PrimaryPressTap => m_Wrapper.m_LeftHand_PrimaryPressTap;
        public InputAction @PrimaryPressHold => m_Wrapper.m_LeftHand_PrimaryPressHold;
        public InputAction @PrimaryPressMultiTap => m_Wrapper.m_LeftHand_PrimaryPressMultiTap;
        public InputAction @SecondaryTouchTap => m_Wrapper.m_LeftHand_SecondaryTouchTap;
        public InputAction @SecondaryTouchHold => m_Wrapper.m_LeftHand_SecondaryTouchHold;
        public InputAction @SecondaryTouchMultiTap => m_Wrapper.m_LeftHand_SecondaryTouchMultiTap;
        public InputAction @SecondaryPressedTap => m_Wrapper.m_LeftHand_SecondaryPressedTap;
        public InputAction @SecondaryPressedHold => m_Wrapper.m_LeftHand_SecondaryPressedHold;
        public InputAction @SecondaryPressedMultiTap => m_Wrapper.m_LeftHand_SecondaryPressedMultiTap;
        public InputAction @Menu => m_Wrapper.m_LeftHand_Menu;
        public InputActionMap Get() { return m_Wrapper.m_LeftHand; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(LeftHandActions set) { return set.Get(); }
        public void AddCallbacks(ILeftHandActions instance)
        {
            if (instance == null || m_Wrapper.m_LeftHandActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_LeftHandActionsCallbackInterfaces.Add(instance);
            @JoyStickMove.started += instance.OnJoyStickMove;
            @JoyStickMove.performed += instance.OnJoyStickMove;
            @JoyStickMove.canceled += instance.OnJoyStickMove;
            @TriggerTouchTap.started += instance.OnTriggerTouchTap;
            @TriggerTouchTap.performed += instance.OnTriggerTouchTap;
            @TriggerTouchTap.canceled += instance.OnTriggerTouchTap;
            @TriggerTouchHold.started += instance.OnTriggerTouchHold;
            @TriggerTouchHold.performed += instance.OnTriggerTouchHold;
            @TriggerTouchHold.canceled += instance.OnTriggerTouchHold;
            @TriggerTouchMultiTap.started += instance.OnTriggerTouchMultiTap;
            @TriggerTouchMultiTap.performed += instance.OnTriggerTouchMultiTap;
            @TriggerTouchMultiTap.canceled += instance.OnTriggerTouchMultiTap;
            @TriggerPressedTap.started += instance.OnTriggerPressedTap;
            @TriggerPressedTap.performed += instance.OnTriggerPressedTap;
            @TriggerPressedTap.canceled += instance.OnTriggerPressedTap;
            @TriggerPressHold.started += instance.OnTriggerPressHold;
            @TriggerPressHold.performed += instance.OnTriggerPressHold;
            @TriggerPressHold.canceled += instance.OnTriggerPressHold;
            @TriggerPressMultiTap.started += instance.OnTriggerPressMultiTap;
            @TriggerPressMultiTap.performed += instance.OnTriggerPressMultiTap;
            @TriggerPressMultiTap.canceled += instance.OnTriggerPressMultiTap;
            @GripPressTap.started += instance.OnGripPressTap;
            @GripPressTap.performed += instance.OnGripPressTap;
            @GripPressTap.canceled += instance.OnGripPressTap;
            @GripPressHold.started += instance.OnGripPressHold;
            @GripPressHold.performed += instance.OnGripPressHold;
            @GripPressHold.canceled += instance.OnGripPressHold;
            @GripPressMultiTap.started += instance.OnGripPressMultiTap;
            @GripPressMultiTap.performed += instance.OnGripPressMultiTap;
            @GripPressMultiTap.canceled += instance.OnGripPressMultiTap;
            @PrimaryTouchTap.started += instance.OnPrimaryTouchTap;
            @PrimaryTouchTap.performed += instance.OnPrimaryTouchTap;
            @PrimaryTouchTap.canceled += instance.OnPrimaryTouchTap;
            @PrimaryTouchHold.started += instance.OnPrimaryTouchHold;
            @PrimaryTouchHold.performed += instance.OnPrimaryTouchHold;
            @PrimaryTouchHold.canceled += instance.OnPrimaryTouchHold;
            @PrimaryTouchMultiTap.started += instance.OnPrimaryTouchMultiTap;
            @PrimaryTouchMultiTap.performed += instance.OnPrimaryTouchMultiTap;
            @PrimaryTouchMultiTap.canceled += instance.OnPrimaryTouchMultiTap;
            @PrimaryPressTap.started += instance.OnPrimaryPressTap;
            @PrimaryPressTap.performed += instance.OnPrimaryPressTap;
            @PrimaryPressTap.canceled += instance.OnPrimaryPressTap;
            @PrimaryPressHold.started += instance.OnPrimaryPressHold;
            @PrimaryPressHold.performed += instance.OnPrimaryPressHold;
            @PrimaryPressHold.canceled += instance.OnPrimaryPressHold;
            @PrimaryPressMultiTap.started += instance.OnPrimaryPressMultiTap;
            @PrimaryPressMultiTap.performed += instance.OnPrimaryPressMultiTap;
            @PrimaryPressMultiTap.canceled += instance.OnPrimaryPressMultiTap;
            @SecondaryTouchTap.started += instance.OnSecondaryTouchTap;
            @SecondaryTouchTap.performed += instance.OnSecondaryTouchTap;
            @SecondaryTouchTap.canceled += instance.OnSecondaryTouchTap;
            @SecondaryTouchHold.started += instance.OnSecondaryTouchHold;
            @SecondaryTouchHold.performed += instance.OnSecondaryTouchHold;
            @SecondaryTouchHold.canceled += instance.OnSecondaryTouchHold;
            @SecondaryTouchMultiTap.started += instance.OnSecondaryTouchMultiTap;
            @SecondaryTouchMultiTap.performed += instance.OnSecondaryTouchMultiTap;
            @SecondaryTouchMultiTap.canceled += instance.OnSecondaryTouchMultiTap;
            @SecondaryPressedTap.started += instance.OnSecondaryPressedTap;
            @SecondaryPressedTap.performed += instance.OnSecondaryPressedTap;
            @SecondaryPressedTap.canceled += instance.OnSecondaryPressedTap;
            @SecondaryPressedHold.started += instance.OnSecondaryPressedHold;
            @SecondaryPressedHold.performed += instance.OnSecondaryPressedHold;
            @SecondaryPressedHold.canceled += instance.OnSecondaryPressedHold;
            @SecondaryPressedMultiTap.started += instance.OnSecondaryPressedMultiTap;
            @SecondaryPressedMultiTap.performed += instance.OnSecondaryPressedMultiTap;
            @SecondaryPressedMultiTap.canceled += instance.OnSecondaryPressedMultiTap;
            @Menu.started += instance.OnMenu;
            @Menu.performed += instance.OnMenu;
            @Menu.canceled += instance.OnMenu;
        }

        private void UnregisterCallbacks(ILeftHandActions instance)
        {
            @JoyStickMove.started -= instance.OnJoyStickMove;
            @JoyStickMove.performed -= instance.OnJoyStickMove;
            @JoyStickMove.canceled -= instance.OnJoyStickMove;
            @TriggerTouchTap.started -= instance.OnTriggerTouchTap;
            @TriggerTouchTap.performed -= instance.OnTriggerTouchTap;
            @TriggerTouchTap.canceled -= instance.OnTriggerTouchTap;
            @TriggerTouchHold.started -= instance.OnTriggerTouchHold;
            @TriggerTouchHold.performed -= instance.OnTriggerTouchHold;
            @TriggerTouchHold.canceled -= instance.OnTriggerTouchHold;
            @TriggerTouchMultiTap.started -= instance.OnTriggerTouchMultiTap;
            @TriggerTouchMultiTap.performed -= instance.OnTriggerTouchMultiTap;
            @TriggerTouchMultiTap.canceled -= instance.OnTriggerTouchMultiTap;
            @TriggerPressedTap.started -= instance.OnTriggerPressedTap;
            @TriggerPressedTap.performed -= instance.OnTriggerPressedTap;
            @TriggerPressedTap.canceled -= instance.OnTriggerPressedTap;
            @TriggerPressHold.started -= instance.OnTriggerPressHold;
            @TriggerPressHold.performed -= instance.OnTriggerPressHold;
            @TriggerPressHold.canceled -= instance.OnTriggerPressHold;
            @TriggerPressMultiTap.started -= instance.OnTriggerPressMultiTap;
            @TriggerPressMultiTap.performed -= instance.OnTriggerPressMultiTap;
            @TriggerPressMultiTap.canceled -= instance.OnTriggerPressMultiTap;
            @GripPressTap.started -= instance.OnGripPressTap;
            @GripPressTap.performed -= instance.OnGripPressTap;
            @GripPressTap.canceled -= instance.OnGripPressTap;
            @GripPressHold.started -= instance.OnGripPressHold;
            @GripPressHold.performed -= instance.OnGripPressHold;
            @GripPressHold.canceled -= instance.OnGripPressHold;
            @GripPressMultiTap.started -= instance.OnGripPressMultiTap;
            @GripPressMultiTap.performed -= instance.OnGripPressMultiTap;
            @GripPressMultiTap.canceled -= instance.OnGripPressMultiTap;
            @PrimaryTouchTap.started -= instance.OnPrimaryTouchTap;
            @PrimaryTouchTap.performed -= instance.OnPrimaryTouchTap;
            @PrimaryTouchTap.canceled -= instance.OnPrimaryTouchTap;
            @PrimaryTouchHold.started -= instance.OnPrimaryTouchHold;
            @PrimaryTouchHold.performed -= instance.OnPrimaryTouchHold;
            @PrimaryTouchHold.canceled -= instance.OnPrimaryTouchHold;
            @PrimaryTouchMultiTap.started -= instance.OnPrimaryTouchMultiTap;
            @PrimaryTouchMultiTap.performed -= instance.OnPrimaryTouchMultiTap;
            @PrimaryTouchMultiTap.canceled -= instance.OnPrimaryTouchMultiTap;
            @PrimaryPressTap.started -= instance.OnPrimaryPressTap;
            @PrimaryPressTap.performed -= instance.OnPrimaryPressTap;
            @PrimaryPressTap.canceled -= instance.OnPrimaryPressTap;
            @PrimaryPressHold.started -= instance.OnPrimaryPressHold;
            @PrimaryPressHold.performed -= instance.OnPrimaryPressHold;
            @PrimaryPressHold.canceled -= instance.OnPrimaryPressHold;
            @PrimaryPressMultiTap.started -= instance.OnPrimaryPressMultiTap;
            @PrimaryPressMultiTap.performed -= instance.OnPrimaryPressMultiTap;
            @PrimaryPressMultiTap.canceled -= instance.OnPrimaryPressMultiTap;
            @SecondaryTouchTap.started -= instance.OnSecondaryTouchTap;
            @SecondaryTouchTap.performed -= instance.OnSecondaryTouchTap;
            @SecondaryTouchTap.canceled -= instance.OnSecondaryTouchTap;
            @SecondaryTouchHold.started -= instance.OnSecondaryTouchHold;
            @SecondaryTouchHold.performed -= instance.OnSecondaryTouchHold;
            @SecondaryTouchHold.canceled -= instance.OnSecondaryTouchHold;
            @SecondaryTouchMultiTap.started -= instance.OnSecondaryTouchMultiTap;
            @SecondaryTouchMultiTap.performed -= instance.OnSecondaryTouchMultiTap;
            @SecondaryTouchMultiTap.canceled -= instance.OnSecondaryTouchMultiTap;
            @SecondaryPressedTap.started -= instance.OnSecondaryPressedTap;
            @SecondaryPressedTap.performed -= instance.OnSecondaryPressedTap;
            @SecondaryPressedTap.canceled -= instance.OnSecondaryPressedTap;
            @SecondaryPressedHold.started -= instance.OnSecondaryPressedHold;
            @SecondaryPressedHold.performed -= instance.OnSecondaryPressedHold;
            @SecondaryPressedHold.canceled -= instance.OnSecondaryPressedHold;
            @SecondaryPressedMultiTap.started -= instance.OnSecondaryPressedMultiTap;
            @SecondaryPressedMultiTap.performed -= instance.OnSecondaryPressedMultiTap;
            @SecondaryPressedMultiTap.canceled -= instance.OnSecondaryPressedMultiTap;
            @Menu.started -= instance.OnMenu;
            @Menu.performed -= instance.OnMenu;
            @Menu.canceled -= instance.OnMenu;
        }

        public void RemoveCallbacks(ILeftHandActions instance)
        {
            if (m_Wrapper.m_LeftHandActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ILeftHandActions instance)
        {
            foreach (var item in m_Wrapper.m_LeftHandActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_LeftHandActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public LeftHandActions @LeftHand => new LeftHandActions(this);

    // RightHand
    private readonly InputActionMap m_RightHand;
    private List<IRightHandActions> m_RightHandActionsCallbackInterfaces = new List<IRightHandActions>();
    private readonly InputAction m_RightHand_JoyStickMove;
    private readonly InputAction m_RightHand_TriggerTouchTap;
    private readonly InputAction m_RightHand_TriggerTouchHold;
    private readonly InputAction m_RightHand_TriggerTouchMultiTap;
    private readonly InputAction m_RightHand_TriggerPressedTap;
    private readonly InputAction m_RightHand_TriggerPressHold;
    private readonly InputAction m_RightHand_TriggerPressMultiTap;
    private readonly InputAction m_RightHand_GripPressTap;
    private readonly InputAction m_RightHand_GripPressHold;
    private readonly InputAction m_RightHand_GripPressMultiTap;
    private readonly InputAction m_RightHand_PrimaryTouchTap;
    private readonly InputAction m_RightHand_PrimaryTouchHold;
    private readonly InputAction m_RightHand_PrimaryTouchMultiTap;
    private readonly InputAction m_RightHand_PrimaryPressTap;
    private readonly InputAction m_RightHand_PrimaryPressHold;
    private readonly InputAction m_RightHand_PrimaryPressMultiTap;
    private readonly InputAction m_RightHand_SecondaryTouchTap;
    private readonly InputAction m_RightHand_SecondaryTouchHold;
    private readonly InputAction m_RightHand_SecondaryTouchMultiTap;
    private readonly InputAction m_RightHand_SecondaryPressedMultiTap;
    private readonly InputAction m_RightHand_SecondaryPressedHold;
    private readonly InputAction m_RightHand_SecondaryPressedTap;
    private readonly InputAction m_RightHand_Menu;
    public struct RightHandActions
    {
        private @InputActions m_Wrapper;
        public RightHandActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @JoyStickMove => m_Wrapper.m_RightHand_JoyStickMove;
        public InputAction @TriggerTouchTap => m_Wrapper.m_RightHand_TriggerTouchTap;
        public InputAction @TriggerTouchHold => m_Wrapper.m_RightHand_TriggerTouchHold;
        public InputAction @TriggerTouchMultiTap => m_Wrapper.m_RightHand_TriggerTouchMultiTap;
        public InputAction @TriggerPressedTap => m_Wrapper.m_RightHand_TriggerPressedTap;
        public InputAction @TriggerPressHold => m_Wrapper.m_RightHand_TriggerPressHold;
        public InputAction @TriggerPressMultiTap => m_Wrapper.m_RightHand_TriggerPressMultiTap;
        public InputAction @GripPressTap => m_Wrapper.m_RightHand_GripPressTap;
        public InputAction @GripPressHold => m_Wrapper.m_RightHand_GripPressHold;
        public InputAction @GripPressMultiTap => m_Wrapper.m_RightHand_GripPressMultiTap;
        public InputAction @PrimaryTouchTap => m_Wrapper.m_RightHand_PrimaryTouchTap;
        public InputAction @PrimaryTouchHold => m_Wrapper.m_RightHand_PrimaryTouchHold;
        public InputAction @PrimaryTouchMultiTap => m_Wrapper.m_RightHand_PrimaryTouchMultiTap;
        public InputAction @PrimaryPressTap => m_Wrapper.m_RightHand_PrimaryPressTap;
        public InputAction @PrimaryPressHold => m_Wrapper.m_RightHand_PrimaryPressHold;
        public InputAction @PrimaryPressMultiTap => m_Wrapper.m_RightHand_PrimaryPressMultiTap;
        public InputAction @SecondaryTouchTap => m_Wrapper.m_RightHand_SecondaryTouchTap;
        public InputAction @SecondaryTouchHold => m_Wrapper.m_RightHand_SecondaryTouchHold;
        public InputAction @SecondaryTouchMultiTap => m_Wrapper.m_RightHand_SecondaryTouchMultiTap;
        public InputAction @SecondaryPressedMultiTap => m_Wrapper.m_RightHand_SecondaryPressedMultiTap;
        public InputAction @SecondaryPressedHold => m_Wrapper.m_RightHand_SecondaryPressedHold;
        public InputAction @SecondaryPressedTap => m_Wrapper.m_RightHand_SecondaryPressedTap;
        public InputAction @Menu => m_Wrapper.m_RightHand_Menu;
        public InputActionMap Get() { return m_Wrapper.m_RightHand; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(RightHandActions set) { return set.Get(); }
        public void AddCallbacks(IRightHandActions instance)
        {
            if (instance == null || m_Wrapper.m_RightHandActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_RightHandActionsCallbackInterfaces.Add(instance);
            @JoyStickMove.started += instance.OnJoyStickMove;
            @JoyStickMove.performed += instance.OnJoyStickMove;
            @JoyStickMove.canceled += instance.OnJoyStickMove;
            @TriggerTouchTap.started += instance.OnTriggerTouchTap;
            @TriggerTouchTap.performed += instance.OnTriggerTouchTap;
            @TriggerTouchTap.canceled += instance.OnTriggerTouchTap;
            @TriggerTouchHold.started += instance.OnTriggerTouchHold;
            @TriggerTouchHold.performed += instance.OnTriggerTouchHold;
            @TriggerTouchHold.canceled += instance.OnTriggerTouchHold;
            @TriggerTouchMultiTap.started += instance.OnTriggerTouchMultiTap;
            @TriggerTouchMultiTap.performed += instance.OnTriggerTouchMultiTap;
            @TriggerTouchMultiTap.canceled += instance.OnTriggerTouchMultiTap;
            @TriggerPressedTap.started += instance.OnTriggerPressedTap;
            @TriggerPressedTap.performed += instance.OnTriggerPressedTap;
            @TriggerPressedTap.canceled += instance.OnTriggerPressedTap;
            @TriggerPressHold.started += instance.OnTriggerPressHold;
            @TriggerPressHold.performed += instance.OnTriggerPressHold;
            @TriggerPressHold.canceled += instance.OnTriggerPressHold;
            @TriggerPressMultiTap.started += instance.OnTriggerPressMultiTap;
            @TriggerPressMultiTap.performed += instance.OnTriggerPressMultiTap;
            @TriggerPressMultiTap.canceled += instance.OnTriggerPressMultiTap;
            @GripPressTap.started += instance.OnGripPressTap;
            @GripPressTap.performed += instance.OnGripPressTap;
            @GripPressTap.canceled += instance.OnGripPressTap;
            @GripPressHold.started += instance.OnGripPressHold;
            @GripPressHold.performed += instance.OnGripPressHold;
            @GripPressHold.canceled += instance.OnGripPressHold;
            @GripPressMultiTap.started += instance.OnGripPressMultiTap;
            @GripPressMultiTap.performed += instance.OnGripPressMultiTap;
            @GripPressMultiTap.canceled += instance.OnGripPressMultiTap;
            @PrimaryTouchTap.started += instance.OnPrimaryTouchTap;
            @PrimaryTouchTap.performed += instance.OnPrimaryTouchTap;
            @PrimaryTouchTap.canceled += instance.OnPrimaryTouchTap;
            @PrimaryTouchHold.started += instance.OnPrimaryTouchHold;
            @PrimaryTouchHold.performed += instance.OnPrimaryTouchHold;
            @PrimaryTouchHold.canceled += instance.OnPrimaryTouchHold;
            @PrimaryTouchMultiTap.started += instance.OnPrimaryTouchMultiTap;
            @PrimaryTouchMultiTap.performed += instance.OnPrimaryTouchMultiTap;
            @PrimaryTouchMultiTap.canceled += instance.OnPrimaryTouchMultiTap;
            @PrimaryPressTap.started += instance.OnPrimaryPressTap;
            @PrimaryPressTap.performed += instance.OnPrimaryPressTap;
            @PrimaryPressTap.canceled += instance.OnPrimaryPressTap;
            @PrimaryPressHold.started += instance.OnPrimaryPressHold;
            @PrimaryPressHold.performed += instance.OnPrimaryPressHold;
            @PrimaryPressHold.canceled += instance.OnPrimaryPressHold;
            @PrimaryPressMultiTap.started += instance.OnPrimaryPressMultiTap;
            @PrimaryPressMultiTap.performed += instance.OnPrimaryPressMultiTap;
            @PrimaryPressMultiTap.canceled += instance.OnPrimaryPressMultiTap;
            @SecondaryTouchTap.started += instance.OnSecondaryTouchTap;
            @SecondaryTouchTap.performed += instance.OnSecondaryTouchTap;
            @SecondaryTouchTap.canceled += instance.OnSecondaryTouchTap;
            @SecondaryTouchHold.started += instance.OnSecondaryTouchHold;
            @SecondaryTouchHold.performed += instance.OnSecondaryTouchHold;
            @SecondaryTouchHold.canceled += instance.OnSecondaryTouchHold;
            @SecondaryTouchMultiTap.started += instance.OnSecondaryTouchMultiTap;
            @SecondaryTouchMultiTap.performed += instance.OnSecondaryTouchMultiTap;
            @SecondaryTouchMultiTap.canceled += instance.OnSecondaryTouchMultiTap;
            @SecondaryPressedMultiTap.started += instance.OnSecondaryPressedMultiTap;
            @SecondaryPressedMultiTap.performed += instance.OnSecondaryPressedMultiTap;
            @SecondaryPressedMultiTap.canceled += instance.OnSecondaryPressedMultiTap;
            @SecondaryPressedHold.started += instance.OnSecondaryPressedHold;
            @SecondaryPressedHold.performed += instance.OnSecondaryPressedHold;
            @SecondaryPressedHold.canceled += instance.OnSecondaryPressedHold;
            @SecondaryPressedTap.started += instance.OnSecondaryPressedTap;
            @SecondaryPressedTap.performed += instance.OnSecondaryPressedTap;
            @SecondaryPressedTap.canceled += instance.OnSecondaryPressedTap;
            @Menu.started += instance.OnMenu;
            @Menu.performed += instance.OnMenu;
            @Menu.canceled += instance.OnMenu;
        }

        private void UnregisterCallbacks(IRightHandActions instance)
        {
            @JoyStickMove.started -= instance.OnJoyStickMove;
            @JoyStickMove.performed -= instance.OnJoyStickMove;
            @JoyStickMove.canceled -= instance.OnJoyStickMove;
            @TriggerTouchTap.started -= instance.OnTriggerTouchTap;
            @TriggerTouchTap.performed -= instance.OnTriggerTouchTap;
            @TriggerTouchTap.canceled -= instance.OnTriggerTouchTap;
            @TriggerTouchHold.started -= instance.OnTriggerTouchHold;
            @TriggerTouchHold.performed -= instance.OnTriggerTouchHold;
            @TriggerTouchHold.canceled -= instance.OnTriggerTouchHold;
            @TriggerTouchMultiTap.started -= instance.OnTriggerTouchMultiTap;
            @TriggerTouchMultiTap.performed -= instance.OnTriggerTouchMultiTap;
            @TriggerTouchMultiTap.canceled -= instance.OnTriggerTouchMultiTap;
            @TriggerPressedTap.started -= instance.OnTriggerPressedTap;
            @TriggerPressedTap.performed -= instance.OnTriggerPressedTap;
            @TriggerPressedTap.canceled -= instance.OnTriggerPressedTap;
            @TriggerPressHold.started -= instance.OnTriggerPressHold;
            @TriggerPressHold.performed -= instance.OnTriggerPressHold;
            @TriggerPressHold.canceled -= instance.OnTriggerPressHold;
            @TriggerPressMultiTap.started -= instance.OnTriggerPressMultiTap;
            @TriggerPressMultiTap.performed -= instance.OnTriggerPressMultiTap;
            @TriggerPressMultiTap.canceled -= instance.OnTriggerPressMultiTap;
            @GripPressTap.started -= instance.OnGripPressTap;
            @GripPressTap.performed -= instance.OnGripPressTap;
            @GripPressTap.canceled -= instance.OnGripPressTap;
            @GripPressHold.started -= instance.OnGripPressHold;
            @GripPressHold.performed -= instance.OnGripPressHold;
            @GripPressHold.canceled -= instance.OnGripPressHold;
            @GripPressMultiTap.started -= instance.OnGripPressMultiTap;
            @GripPressMultiTap.performed -= instance.OnGripPressMultiTap;
            @GripPressMultiTap.canceled -= instance.OnGripPressMultiTap;
            @PrimaryTouchTap.started -= instance.OnPrimaryTouchTap;
            @PrimaryTouchTap.performed -= instance.OnPrimaryTouchTap;
            @PrimaryTouchTap.canceled -= instance.OnPrimaryTouchTap;
            @PrimaryTouchHold.started -= instance.OnPrimaryTouchHold;
            @PrimaryTouchHold.performed -= instance.OnPrimaryTouchHold;
            @PrimaryTouchHold.canceled -= instance.OnPrimaryTouchHold;
            @PrimaryTouchMultiTap.started -= instance.OnPrimaryTouchMultiTap;
            @PrimaryTouchMultiTap.performed -= instance.OnPrimaryTouchMultiTap;
            @PrimaryTouchMultiTap.canceled -= instance.OnPrimaryTouchMultiTap;
            @PrimaryPressTap.started -= instance.OnPrimaryPressTap;
            @PrimaryPressTap.performed -= instance.OnPrimaryPressTap;
            @PrimaryPressTap.canceled -= instance.OnPrimaryPressTap;
            @PrimaryPressHold.started -= instance.OnPrimaryPressHold;
            @PrimaryPressHold.performed -= instance.OnPrimaryPressHold;
            @PrimaryPressHold.canceled -= instance.OnPrimaryPressHold;
            @PrimaryPressMultiTap.started -= instance.OnPrimaryPressMultiTap;
            @PrimaryPressMultiTap.performed -= instance.OnPrimaryPressMultiTap;
            @PrimaryPressMultiTap.canceled -= instance.OnPrimaryPressMultiTap;
            @SecondaryTouchTap.started -= instance.OnSecondaryTouchTap;
            @SecondaryTouchTap.performed -= instance.OnSecondaryTouchTap;
            @SecondaryTouchTap.canceled -= instance.OnSecondaryTouchTap;
            @SecondaryTouchHold.started -= instance.OnSecondaryTouchHold;
            @SecondaryTouchHold.performed -= instance.OnSecondaryTouchHold;
            @SecondaryTouchHold.canceled -= instance.OnSecondaryTouchHold;
            @SecondaryTouchMultiTap.started -= instance.OnSecondaryTouchMultiTap;
            @SecondaryTouchMultiTap.performed -= instance.OnSecondaryTouchMultiTap;
            @SecondaryTouchMultiTap.canceled -= instance.OnSecondaryTouchMultiTap;
            @SecondaryPressedMultiTap.started -= instance.OnSecondaryPressedMultiTap;
            @SecondaryPressedMultiTap.performed -= instance.OnSecondaryPressedMultiTap;
            @SecondaryPressedMultiTap.canceled -= instance.OnSecondaryPressedMultiTap;
            @SecondaryPressedHold.started -= instance.OnSecondaryPressedHold;
            @SecondaryPressedHold.performed -= instance.OnSecondaryPressedHold;
            @SecondaryPressedHold.canceled -= instance.OnSecondaryPressedHold;
            @SecondaryPressedTap.started -= instance.OnSecondaryPressedTap;
            @SecondaryPressedTap.performed -= instance.OnSecondaryPressedTap;
            @SecondaryPressedTap.canceled -= instance.OnSecondaryPressedTap;
            @Menu.started -= instance.OnMenu;
            @Menu.performed -= instance.OnMenu;
            @Menu.canceled -= instance.OnMenu;
        }

        public void RemoveCallbacks(IRightHandActions instance)
        {
            if (m_Wrapper.m_RightHandActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IRightHandActions instance)
        {
            foreach (var item in m_Wrapper.m_RightHandActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_RightHandActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public RightHandActions @RightHand => new RightHandActions(this);
    public interface ILeftHandActions
    {
        void OnJoyStickMove(InputAction.CallbackContext context);
        void OnTriggerTouchTap(InputAction.CallbackContext context);
        void OnTriggerTouchHold(InputAction.CallbackContext context);
        void OnTriggerTouchMultiTap(InputAction.CallbackContext context);
        void OnTriggerPressedTap(InputAction.CallbackContext context);
        void OnTriggerPressHold(InputAction.CallbackContext context);
        void OnTriggerPressMultiTap(InputAction.CallbackContext context);
        void OnGripPressTap(InputAction.CallbackContext context);
        void OnGripPressHold(InputAction.CallbackContext context);
        void OnGripPressMultiTap(InputAction.CallbackContext context);
        void OnPrimaryTouchTap(InputAction.CallbackContext context);
        void OnPrimaryTouchHold(InputAction.CallbackContext context);
        void OnPrimaryTouchMultiTap(InputAction.CallbackContext context);
        void OnPrimaryPressTap(InputAction.CallbackContext context);
        void OnPrimaryPressHold(InputAction.CallbackContext context);
        void OnPrimaryPressMultiTap(InputAction.CallbackContext context);
        void OnSecondaryTouchTap(InputAction.CallbackContext context);
        void OnSecondaryTouchHold(InputAction.CallbackContext context);
        void OnSecondaryTouchMultiTap(InputAction.CallbackContext context);
        void OnSecondaryPressedTap(InputAction.CallbackContext context);
        void OnSecondaryPressedHold(InputAction.CallbackContext context);
        void OnSecondaryPressedMultiTap(InputAction.CallbackContext context);
        void OnMenu(InputAction.CallbackContext context);
    }
    public interface IRightHandActions
    {
        void OnJoyStickMove(InputAction.CallbackContext context);
        void OnTriggerTouchTap(InputAction.CallbackContext context);
        void OnTriggerTouchHold(InputAction.CallbackContext context);
        void OnTriggerTouchMultiTap(InputAction.CallbackContext context);
        void OnTriggerPressedTap(InputAction.CallbackContext context);
        void OnTriggerPressHold(InputAction.CallbackContext context);
        void OnTriggerPressMultiTap(InputAction.CallbackContext context);
        void OnGripPressTap(InputAction.CallbackContext context);
        void OnGripPressHold(InputAction.CallbackContext context);
        void OnGripPressMultiTap(InputAction.CallbackContext context);
        void OnPrimaryTouchTap(InputAction.CallbackContext context);
        void OnPrimaryTouchHold(InputAction.CallbackContext context);
        void OnPrimaryTouchMultiTap(InputAction.CallbackContext context);
        void OnPrimaryPressTap(InputAction.CallbackContext context);
        void OnPrimaryPressHold(InputAction.CallbackContext context);
        void OnPrimaryPressMultiTap(InputAction.CallbackContext context);
        void OnSecondaryTouchTap(InputAction.CallbackContext context);
        void OnSecondaryTouchHold(InputAction.CallbackContext context);
        void OnSecondaryTouchMultiTap(InputAction.CallbackContext context);
        void OnSecondaryPressedMultiTap(InputAction.CallbackContext context);
        void OnSecondaryPressedHold(InputAction.CallbackContext context);
        void OnSecondaryPressedTap(InputAction.CallbackContext context);
        void OnMenu(InputAction.CallbackContext context);
    }
}
